name: Style

on:
  push:
    branches:
      - master
      - main
  pull_request:
    branches:
      - master
      - main

env:
  CPM_SOURCE_CACHE: ${{ github.workspace }}/cpm_modules

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/cache@v2
        with:
          path: "**/cpm_modules"
          key: ${{ github.workflow }}-cpm-modules-${{ hashFiles('**/CMakeLists.txt', '**/*.cmake') }}

      - name: Setup Miniconda
        # You may pin to the exact commit or the version.
        # uses: conda-incubator/setup-miniconda@35d1405e78aa3f784fe3ce9a2eb378d5eeb62169
        uses: conda-incubator/setup-miniconda@v2.1.1
        with:
          auto-update-conda: ture
          
      - name: Install dependent software
        run: |
          conda info
          conda list
          conda config --show-sources
          conda config --show
          conda install -c conda-forge cmake xtensor xtensor-blas openblas

      - name: Install format dependencies
        run: |
          brew install clang-format
          pip3 install cmake_format==0.6.11 pyyaml

      - name: configure
        run: cmake -Stest -Bbuild

      - name: check style
        run: cmake --build build --target check-format
